export type Element = 'Pyro' | 'Hydro' | 'Anemo' | 'Electro' | 'Cryo' | 'Geo' | 'Dendro';
export type Weapon = 'Sword' | 'Claymore' | 'Polearm' | 'Bow' | 'Catalyst';
export type Role = 'Main DPS' | 'Sub DPS' | 'Support' | 'Healer';
export type Tier = 'S' | 'A' | 'B';

/** One entry of public/genshin/roster.json (generated by the backend's build script). */
export interface RosterCharacter {
  id: number;
  key: string;
  name: { en: string; es: string; pt: string };
  element: Element;
  weapon: Weapon;
  rarity: 4 | 5;
  /** Enka CDN file names (no extension). `sideIcon` is the fallback when `icon` 404s. */
  icon: string;
  sideIcon: string;
}

export interface OwnedCharacter {
  id: number;
  /** Known only for Enka showcase characters. */
  level?: number | null;
  cons?: number;
  source: 'enka' | 'manual';
}

export interface MetaCharacter {
  id: number;
  role: Role;
  tier: Tier;
}

export interface MetaTeam {
  name: string;
  reaction: string;
  tier: Tier;
  members: { id: number; role: Role }[];
  note: string;
}

export interface MetaSource {
  title: string;
  url: string;
}

/** Response of POST /genshin/meta. */
export interface Meta {
  patch: string;
  characters: MetaCharacter[];
  teams: MetaTeam[];
  banners: number[];
  sources: MetaSource[];
  model: string;
  fetchedAt: number;
  cached?: boolean;
  stale?: boolean;
  /** Generated by the backup model: lower quality, banners not asserted, expires fast. */
  degraded?: boolean;
}

/** Response of GET /genshin/profile/{uid}. */
export interface EnkaProfile {
  uid: string;
  nickname: string | null;
  adventureRank: number | null;
  ttl: number;
  showcaseVisible: boolean;
  characters: { id: number; level: number | null; cons: number }[];
}

export type SlotStatus = 'owned' | 'substitute' | 'missing';

export interface ScoredSlot {
  /** Character the meta asks for. */
  wantedId: number;
  role: Role;
  status: SlotStatus;
  /** Who actually fills the slot: the wanted character itself, a substitute, or nobody. */
  fillId: number | null;
  /** 0..~1.12 quality of the filler in this slot. */
  quality: number;
}

export interface ScoredTeam {
  team: MetaTeam;
  /** 0..~112; 100 means a full S-tier team of maxed characters. */
  score: number;
  slots: ScoredSlot[];
  ownedCount: number;
  missingCount: number;
}

export interface PullCandidateResult {
  id: number;
  /** Average score of the best teams after pulling the candidate. */
  newScore: number;
  /** Percent change over the current score. `null` when there is no current score to compare against. */
  improvementPct: number | null;
  /** Teams that include the candidate, best first, with their score if pulled. */
  unlocked: ScoredTeam[];
}
